server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://${study.config.registry.user}:${study.config.registry.password}@${study.config.registry.host}:${study.config.registry.port}/eureka/

study-order:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule